spring:
  quartz:
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 2
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
      platform: mysql
  datasource:
    # type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
