#spring:
#  cache:
#    type: simple

spring:
  cache:
    type: redis
#    cache-names:
#      - multiple
#      - plus
#      - random
    redis:
      time-to-live: 10s
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
