spring:
  jms:
    cache:
      enabled: true
      session-cache-size: 5
  artemis:
    mode: native
    broker-url: tcp://localhost:61616
    user: artemis
    password: artemis
    pool:
      enabled: true
      max-connections: 50
      idle-timeout: 5s
      max-sessions-per-connection: 100